resources:
  containers:
  - container: build_container
    image: msftxlangbuild.azurecr.io/xlang-ubuntu-build
    endpoint: msftxlangbuild

pool:
  vmImage: 'ubuntu-16.04'

container: build_container

steps:
- script: cmake ./src -B_build -GNinja -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_INSTALL_PREFIX=install
  displayName: 'CMake'
- script: ninja -C _build install -v
  displayName: 'Ninja'
- script: ./install/test/library/test_library -r junit -o TEST-test_library.xml
  displayName: 'test_library'
  continueOnError: true
- script: ./install/test/platform/test_platform -r junit -o TEST-test_platform.xml
  displayName: 'test_platform'
  continueOnError: true
- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/TEST-*.xml'  

